source: .
destination: ./_site
include: 
  - '.htaccess'
exclude: 
  - 'VagrantFile'
  - 'bower.json' 
  - 'readme.md'
  - "_source_img"
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files: ['.git']
timezone: Europe/London

host: 0.0.0.0
port: 4000
baseurl: 
url: http://localhost:4000
lsi: false

name: ptheywood.github.io
permalink: /posts/:title
markdown: kramdown
highlighter: rouge

ga_enabled: false

kramdown:
  input: GFM
